---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp belasungkawa.html $DEPLOYPATH
    - /bin/cp perayaan.html $DEPLOYPATH
    - /bin/cp pernikahan.html $DEPLOYPATH
    - /bin/cp shop-s2.html $DEPLOYPATH
    - /bin/cp shop.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH